import 'package:financial_health_dashboard/src/shared/presentation/design/theme/app_semantic_colors.dart';
import 'package:financial_health_dashboard/src/shared/presentation/design/theme/add_income_sheet_theme_ext.dart';
import 'package:financial_health_dashboard/src/shared/presentation/design/theme/financial_health_score_theme_ext.dart';
import 'package:financial_health_dashboard/src/shared/presentation/design/theme/flow_analysis_theme_ext.dart';
import 'package:financial_health_dashboard/src/shared/presentation/design/theme/monthly_goal_theme_ext.dart';
import 'package:flutter/material.dart';

final ThemeData appLightTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  scaffoldBackgroundColor: const Color(0xFFF8FAFA),
  fontFamily: 'Inter',
  extensions: const <ThemeExtension<dynamic>>[
    AppSemanticColors(
      backgroundPrimary: Color(0xFFF8FAFA),
      headerTitle: Color(0xFF2D3435),
      headerSubtitle: Color(0xFF596061),
      headerActionBackground: Color(0xFFDDE4E4),
      headerActionIcon: Color(0xFF2D3435),
      headerMenuBackground: Color(0xFFFFFFFF),
      headerMenuBorder: Color(0x33ACB3B4),
      headerMenuText: Color(0xFF2D3435),
      headerMenuIcon: Color(0xFF2D3435),
      headerMenuShadow: Color(0x19000000),
      metricCardBackground: Color(0xFFFFFFFF),
      metricCardBorder: Color(0x00FFFFFF),
      metricCardShadow: Color(0x0A2D3435),
      metricCardIcon: Color(0xFF2D6957),
      metricCardIconRed: Color(0xFFA83836),

      metricCardLabel: Color(0xFF596061),
      metricCardValue: Color(0xFF2D3435),
    ),
    FinancialHealthScoreTheme(
      healthy: FinancialHealthCardColors(
        backgroundStart: Color(0xFF2D6957),
        backgroundEnd: Color(0xFF1F5D4B),
        backgroundSolid: Color(0xFF2D6957),
        badgeBackground: Color(0xFFB1EFD8),
        badgeText: Color(0xFF1D5C4A),
        titleText: Color(0xFFE4FFF3),
        scoreText: Color(0xFFE4FFF3),
        scoreSuffixText: Color(0xFFE4FFF3),
        headlineText: Color(0xFFE4FFF3),
        descriptionText: Color(0xFFE4FFF3),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0x99E4FFF3),
        borderColor: Color(0x00000000),
        shadowColor: Color(0x262D6957),
        useGradient: true,
      ),
      attention: FinancialHealthCardColors(
        backgroundStart: Color(0xFF2D6957),
        backgroundEnd: Color(0xFF1F5D4B),
        backgroundSolid: Color(0xFF2D6957),
        badgeBackground: Color(0xFFB1EFD8),
        badgeText: Color(0xFF1D5C4A),
        titleText: Color(0xFFE4FFF3),
        scoreText: Color(0xFFE4FFF3),
        scoreSuffixText: Color(0xFFE4FFF3),
        headlineText: Color(0xFFE4FFF3),
        descriptionText: Color(0xFFE4FFF3),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0x99E4FFF3),
        borderColor: Color(0x00000000),
        shadowColor: Color(0x262D6957),
        useGradient: true,
      ),
      critical: FinancialHealthCardColors(
        backgroundStart: Color(0xFFA83836),
        backgroundEnd: Color(0xFF67040D),
        backgroundSolid: Color(0xFFA83836),
        badgeBackground: Color(0xFFFA746F),
        badgeText: Color(0xFF6E0A12),
        titleText: Color(0xFFE4FFF3),
        scoreText: Color(0xFFE4FFF3),
        scoreSuffixText: Color(0xFFE4FFF3),
        headlineText: Color(0xFFE4FFF3),
        descriptionText: Color(0xFFE4FFF3),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0x99E4FFF3),
        borderColor: Color(0x00000000),
        shadowColor: Color(0x26000000),
        useGradient: true,
      ),
    ),
    FlowAnalysisTheme(
      sectionTitle: Color(0xFF2D3435),
      cardBackground: Color(0xFFFFFFFF),
      cardBorder: Color(0x00FFFFFF),
      cardShadow: Color(0x0A2D3435),
      cardTitle: Color(0xFF2D3435),
      message: Color(0xFF596061),
      incomeBase: Color(0xFFA3E1CA),
      incomeHighlight: Color(0xFF2D6957),
      expenseBase: Color(0xFFA83836),
      expenseHighlight: Color(0xFFA83836),
    ),
    MonthlyGoalTheme(
      positive: MonthlyGoalCardColors(
        background: Color(0xFFB1EFD8),
        border: Color(0x00000000),
        shadow: Color(0x00000000),
        title: Color(0xFF1D5C4A),
        description: Color(0xCC1D5C4A),
        iconColor: Color(0xFF1D5C4A),
      ),
      negative: MonthlyGoalCardColors(
        background: Color(0xFFFFB4AB),
        border: Color(0x19BA1A1A),
        shadow: Color(0x0C000000),
        title: Color(0xFF410002),
        description: Color(0xB2410002),
        iconColor: Color(0xFF410002),
      ),
    ),
    AddIncomeSheetTheme(
      background: Color(0xFFFFFFFF),
      dragHandle: Color(0x4CACB3B4),
      title: Color(0xFF2D3435),
      closeButtonBackground: Color(0xFFEAEFEF),
      closeIcon: Color(0xFF2D3435),
      fieldLabel: Color(0xFF596061),
      fieldBackground: Color(0xFFF0F4F4),
      fieldText: Color(0xFF2D3435),
      fieldPlaceholder: Color(0xFFACB3B4),
      currencySymbol: Color(0xFF2D6957),
      categorySelectedBackground: Color(0xFFB1EFD8),
      categorySelectedText: Color(0xFF2D6957),
      categorySelectedIcon: Color(0xFF2D6957),
      categoryUnselectedBackground: Color(0xFFEAEFEF),
      categoryUnselectedText: Color(0xFF596061),
      categoryUnselectedIcon: Color(0xFF596061),
      categoryAddBackground: Color(0xFFEAEFEF),
      categoryAddIcon: Color(0xFF596061),
      primaryButtonStart: Color(0xFF2D6957),
      primaryButtonEnd: Color(0xFF1F5D4B),
      primaryButtonText: Color(0xFFFFFFFF),
      sheetShadow: Color(0x1E2D3435),
    ),
  ],
);

final ThemeData appDarkTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  scaffoldBackgroundColor: const Color(0xFF131313),
  fontFamily: 'Inter',
  extensions: const <ThemeExtension<dynamic>>[
    AppSemanticColors(
      backgroundPrimary: Color(0xFF131313),
      headerTitle: Color(0xFFE1E3E3),
      headerSubtitle: Color(0xFFACB3B4),
      headerActionBackground: Color(0xFF232B2B),
      headerActionIcon: Color(0xFFE1E3E3),
      headerMenuBackground: Color(0xFF18181B),
      headerMenuBorder: Color(0x33ACB3B4),
      headerMenuText: Color(0xFFE5E2E1),
      headerMenuIcon: Color(0xFFE5E2E1),
      headerMenuShadow: Color(0x19000000),
      metricCardBackground: Color(0xFF191E1E),
      metricCardBorder: Color(0x193F4949),
      metricCardShadow: Color(0x00000000),
      metricCardIcon: Color(0xFFB1EFD8),
      metricCardIconRed: Color(0xFFFFB4AB),
      metricCardLabel: Color(0xFFA1A8A9),
      metricCardValue: Color(0xFFE1E3E3),
    ),
    FinancialHealthScoreTheme(
      healthy: FinancialHealthCardColors(
        backgroundStart: Color(0xFF1D4D3F),
        backgroundEnd: Color(0xFF1D4D3F),
        backgroundSolid: Color(0xFF1D4D3F),
        badgeBackground: Color(0xFFA3E1CA),
        badgeText: Color(0xFF004938),
        titleText: Color(0xFFA3E1CA),
        scoreText: Color(0xFFFFFFFF),
        scoreSuffixText: Color(0xFFA3E1CA),
        headlineText: Color(0xFFFFFFFF),
        descriptionText: Color(0xFFA3E1CA),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0xCCA3E1CA),
        borderColor: Color(0x0DFFFFFF),
        shadowColor: Color(0x3F000000),
        useGradient: false,
      ),
      attention: FinancialHealthCardColors(
        backgroundStart: Color(0xFF1D4D3F),
        backgroundEnd: Color(0xFF1D4D3F),
        backgroundSolid: Color(0xFF1D4D3F),
        badgeBackground: Color(0xFFA3E1CA),
        badgeText: Color(0xFF004938),
        titleText: Color(0xFFA3E1CA),
        scoreText: Color(0xFFFFFFFF),
        scoreSuffixText: Color(0xFFA3E1CA),
        headlineText: Color(0xFFFFFFFF),
        descriptionText: Color(0xFFA3E1CA),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0xCCA3E1CA),
        borderColor: Color(0x0DFFFFFF),
        shadowColor: Color(0x3F000000),
        useGradient: false,
      ),
      critical: FinancialHealthCardColors(
        backgroundStart: Color(0xFF4A0404),
        backgroundEnd: Color(0xFF240101),
        backgroundSolid: Color(0xFF4A0404),
        badgeBackground: Color(0xFF93000A),
        badgeText: Color(0xFFFFDAD6),
        titleText: Color(0xFFFFFFFF),
        scoreText: Color(0xFFFFFFFF),
        scoreSuffixText: Color(0xFFFFFFFF),
        headlineText: Color(0xFFFEE2E2),
        descriptionText: Color(0xFFFFFFFF),
        divider: Color(0x1AFFFFFF),
        iconColor: Color(0xCCFFFFFF),
        borderColor: Color(0x4C7F1D1D),
        shadowColor: Color(0x66000000),
        useGradient: true,
      ),
    ),
    FlowAnalysisTheme(
      sectionTitle: Color(0xFFFEFFFC),
      cardBackground: Color(0xFF191C1C),
      cardBorder: Color(0x193F4949),
      cardShadow: Color(0x00000000),
      cardTitle: Color(0xFFE1E3E3),
      message: Color(0xFFBFC8C8),
      incomeBase: Color(0xFFA3E1CA),
      incomeHighlight: Color(0xFFB1EFD8),
      expenseBase: Color(0xFFE57373),
      expenseHighlight: Color(0xFFE57373),
    ),
    MonthlyGoalTheme(
      positive: MonthlyGoalCardColors(
        background: Color(0xFF1D5C4A),
        border: Color(0x33B1EFD8),
        shadow: Color(0x00000000),
        title: Color(0xFFB1EFD8),
        description: Color(0xCCB1EFD8),
        iconColor: Color(0xFFB1EFD8),
      ),
      negative: MonthlyGoalCardColors(
        background: Color(0xFF450A0A),
        border: Color(0x7F7F1D1D),
        shadow: Color(0x00000000),
        title: Color(0xFFFEE2E2),
        description: Color(0xCCFECACA),
        iconColor: Color(0xFFFEE2E2),
      ),
    ),
    AddIncomeSheetTheme(
      background: Color(0xFF2A2A2A),
      dragHandle: Color(0xFF404945),
      title: Color(0xFFFEFFFC),
      closeButtonBackground: Color(0xFF1C1B1B),
      closeIcon: Color(0xFFE5E2E1),
      fieldLabel: Color(0xFF596061),
      fieldBackground: Color(0xFF0E0E0E),
      fieldText: Color(0xFFE5E2E1),
      fieldPlaceholder: Color(0xFF6B7280),
      currencySymbol: Color(0xFF96D3BD),
      categorySelectedBackground: Color(0xFFB1EFD8),
      categorySelectedText: Color(0xFF00382B),
      categorySelectedIcon: Color(0xFF00382B),
      categoryUnselectedBackground: Color(0xFF0E0E0E),
      categoryUnselectedText: Color(0xFFBFC9C3),
      categoryUnselectedIcon: Color(0xFFBFC9C3),
      categoryAddBackground: Color(0xFF0E0E0E),
      categoryAddIcon: Color(0xFFBFC9C3),
      primaryButtonStart: Color(0xFF2D6957),
      primaryButtonEnd: Color(0xFF1F5D4B),
      primaryButtonText: Color(0xFFFFFFFF),
      sheetShadow: Color(0x1E2D3435),
    ),
  ],
);
